### ISSUE TITLE
ionic platform add android error

### ISSUE THREAD

**Issue by esafwan** [driftyco/ionic-box#34]
When am using the  command `ionic platform add android` its giving the below error. 

> Error: EACCES, open '/home/vagrant/.cordova/lib/npm_cache/cordova- android/3.6.4/package/.npmignore'

**Comment by perrygovier** [comment]
It looks like a permissions issue, possibly from an unnecessary sudo command. `sudo chown -R vagrant /home/vagrant/.cordova` should do the trick.

**Comment by esafwan** [comment]
Now I am getting entirely new set of error. I tried the command `android -no-ui` to see if the sdk is in path, and it seems to be correctly placed.

```shell
Creating android project...

/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:126
                    throw e;
                          ^
Error: ANDROID_HOME is not set and "android" command not in your PATH. You must fulfill at least one of these conditions.
    at /home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/lib/check_reqs.js:159:19
    at _fulfilled (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:760:13)
    at /home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:821:14
    at flush (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
Error: /home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/create: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-     lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)

```

**Comment by nachoad** [comment]
I had same error as @esafwan esafwan. Doing the `chmod` and trying to add the android platform, I got this error:
```
vagrant@ionic-android:~/ionic/todo$ ionic platform add android
addCliHookDirectory fs.chmodSync: Error: EPERM, operation not permitted 'hooks/after_platform_add/010_install_plugins.js'
addCliHookDirectory fs.chmodSync: Error: EPERM, operation not permitted 'hooks/after_plugin_add/010_register_plugin.js'
addCliHookDirectory fs.chmodSync: Error: EPERM, operation not permitted 'hooks/after_plugin_rm/010_deregister_plugin.js'
addCliHookDirectory fs.chmodSync: Error: EPERM, operation not permitted 'hooks/after_prepare/010_add_platform_class.js'
addCliHookDirectory fs.chmodSync: Error: EPERM, operation not permitted 'hooks/after_prepare/020_remove_sass_from_platforms.js'
addCliHookDirectory fs.chmodSync: Error: EPERM, operation not permitted 'hooks/before_platform_add/init_directories.js'
Running command: /home/vagrant/ionic/todo/hooks/before_platform_add/init_directories.js /home/vagrant/ionic/todo
Creating android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.ionicframework.todo675384
	Name: todo
	Android target: android-19
Copying template files...
shell.js: internal error
Error: ENOENT, no such file or directory 'platforms/android/assets'
    at Object.fs.mkdirSync (fs.js:647:18)
    at /home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/shelljs/src/cp.js:173:14
    at Array.forEach (native)
    at Object._cp (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/shelljs/src/cp.js:156:11)
    at Object.cp (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/shelljs/src/common.js:172:23)
    at /home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/lib/create.js:247:19
    at setShellFatal (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/lib/create.js:45:5)
    at /home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/lib/create.js:245:9
    at _fulfilled (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:827:30)
Error: /home/vagrant/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/create: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

**Comment by rdgutierrez** [comment]
I have the same problem Error: ANDROID_HOME is not set and "android" command not in your PATH.

**Comment by shamsher31** [comment]
Is anyone got any solution of this error. I'm still facing this issue from long time.

this is my configuration.

export ANDROID_HOME=/Users/shamsher/Documents/android-sdk-macosx
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

When I use sudo ionic platform add android I got this error

/Users/shamsher/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:126
                    throw e;
                          ^
Error: ANDROID_HOME is not set and "android" command not in your PATH. You must fulfill at least one of these conditions.
    at /Users/shamsher/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/lib/check_reqs.js:159:19
    at _fulfilled (/Users/shamsher/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/Users/shamsher/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/Users/shamsher/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:760:13)
    at /Users/shamsher/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:821:14
    at flush (/Users/shamsher/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
Error: /Users/shamsher/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/create: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

And when I use only ionic platform add android I got this error

Error: Attempt to unlock cordova-android@3.6.4, which hasn't been locked
    at unlock (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/utils/locker.js:44:11)
    at cb (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache/add-named.js:32:5)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache/add-named.js:41:20
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/utils/locker.js:30:7
    at cb (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
    at Object.oncomplete (fs.js:107:15)

**Comment by mandymu** [comment]
Same error on Ubuntu 14.04, android SDK running fine, yet!

**Comment by am-een** [comment]
i reinstalled cordova and then I ran: sudo chown -R werewolf /home/werewolf/.cordova
and now it works fine

**Comment by CoHyper** [comment]
Same error on Mac OS X 10.10.3
My solution
* `rm -rf .cordova/` or `rm -rf /Users/svenlang/.cordova/`
* start again and its work

**Comment by achaiah** [comment]
I can confirm that ~/.cordova is still an issue (at least on Mac OS X 10.10.3). Just spent an hour debugging this because "ionic platform add ios" was working fine but "ionic platform add android" was not. None of the other suggestions have helped and I was getting very frustrated. In the end "sudo chmod -R 777 ~/.cordova" did the trick. Arg!

**Comment by hybridappdev** [comment]
I have CoHyper and achaiah solution didn't work for me, i am using Max OS X 10.10.3. I have confirm PATH in ~/.bash_profile as below
export ANDROID_HOME=/Users/User/Library/android-sdk-macosx
export PATH=${PATH}:/usr/local/apache-ant/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

**Comment by achaiah** [comment]
@hybridappdev 

When you run 'sudo' it doesn't take your user's path into account (because you're switching to root). Try without 'sudo'.

**Comment by hybridappdev** [comment]
@achaiah

stil getting same error

**Comment by evanglerm** [comment]
sudo chmod -R 777 ~/.cordova ... Worked. Thanks for all the contributor.

**Comment by hari2111** [comment]
I have this problem in windows.Need help,stuck with this issue

**Comment by SKempin** [comment]
Currently experiencing this issue on Windows 7. @hari2111 Did you find a solution?
