### ISSUE TITLE
gulp-sass error

### ISSUE THREAD

**Issue by paulogr** [driftyco/ionic-box#36]
Hi guys, everytime that I change my scss file I got this error:

Error: /vagrant/projects/ionic-samples/sprtsapp_detail_view/node_modules/gulp-sass/node_modules/node-sass/bin/linux-ia32-v8-3.14/binding.node: wrong ELF class: ELFCLASS64
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at requireBinding (/vagrant/projects/ionic-samples/sprtsapp_detail_view/node_modules/gulp-sass/node_modules/node-sass/sass.js:18:14)
    at Object.<anonymous> (/vagrant/projects/ionic-samples/sprtsapp_detail_view/node_modules/gulp-sass/node_modules/node-sass/sass.js:25:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

Anyone experienced the same issue ? Is there any related with the 32bit ubuntu ?

**Comment by eodgooch** [comment]
Any resolution to this? I have the same error and I suspect it has to do with running vagrant on OSX but I'm stumped how to resolve this - short of using a 64 bit image.

**Comment by Ionitron** [comment]
Greetings @paulogr!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
